name: 'CLI for Microsoft 365 Login'
description: 'Login to tenant using CLI for Microsoft 365'
inputs:
  ADMIN_USERNAME:  
    description: 'Username (email address) of the admin'
    required: true
  ADMIN_PASSWORD:  
    description: 'Password of the admin'
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: 'log-in'  
  color: 'blue'