name: 'Office 365 CLI Login'
description: 'Login to tenant using Office 365 CLI'
inputs:
  ADMIN_USERNAME:  
    description: 'Username (email address) of the admin'
    required: true
  ADMIN_PASSWORD:  
    description: 'Password of the admin'
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: 'log-in'  
  color: 'blue'