export const constants = {
    CLI_NPMINSTALL_COMMAND: 'npm i -g @pnp/cli-microsoft365',
    CLI_PREFIX: 'm365',
    ACTION_ADMIN_USERNAME: 'ADMIN_USERNAME',
    ACTION_ADMIN_PASSWORD: 'ADMIN_PASSWORD',
    ACTION_CERTIFICATE_ENCODED: 'CERTIFICATE_ENCODED',
    ACTION_CERTIFICATE_PASSWORD: 'CERTIFICATE_PASSWORD',
    ACTION_AAD_APP_ID: 'AAD_APP_ID',
    ACTION_TENANT_ID: 'TENANT_ID',
}
