on: [workflow_dispatch]

jobs:
  cli_login_cert_job:
    runs-on: ubuntu-latest
    name: CLI Login Job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: CLI for Microsoft 365 Login
        uses: ./
        id: login
        with:
          APP_ID: ${{ secrets.APP_ID }}
          TENANT: ${{ secrets.TENANT }}
          CERTIFICATE_ENCODED: ${{ secrets.CERTIFICATE_ENCODED }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
